# Generated by Django 3.2 on 2023-03-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Brand Name')),
                ('image', models.ImageField(blank=True, default='images/default.png', help_text='Upload a product image', null=True, upload_to='images/', verbose_name='image')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Brand safe URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', help_text='Upload a Category image', null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
