# Generated by Django 3.2 on 2023-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_image',
            field=models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/', verbose_name='image'),
        ),
    ]
