# Generated by Django 3.2 on 2023-05-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_product_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_feature',
            field=models.BooleanField(default=False, help_text='Mark product feature '),
        ),
    ]
